-- FundedWealth Terminal OS live database contract snapshot
--
-- DOCUMENTATION ONLY. This file is intentionally non-executable.
-- It must not be used as a migration and must not create or alter tables.
-- Verified against Terminal Supabase project nysrxvpjdlvzvcawysvh on 2026-09-18.
--
-- Canonical trading relationships:
--   trading_accounts.trader_id -> terminal_traders.id
--   trading_orders.trading_account_id -> trading_accounts.id
--   executions.order_id -> trading_orders.id
--   executions.position_id -> positions.id
--   executions.trading_account_id -> trading_accounts.id
--   positions.trading_account_id -> trading_accounts.id
--   account_metrics.trading_account_id -> trading_accounts.id
--   risk_events.trading_account_id -> trading_accounts.id
--   watchlists.trader_id -> terminal_traders.id
--
-- Payment and trading orders are separate:
--   orders         = payment / checkout
--   trading_orders = actual trading orders
--
-- LIVE TABLES
--
-- terminal_traders:
--   id uuid, external_id text, email text, display_name text,
--   avatar_url text, plan text, status text, preferences jsonb,
--   last_login_at timestamptz, created_at timestamptz, updated_at timestamptz
--
-- trading_accounts:
--   id uuid, trader_id uuid, challenge_id uuid, account_code text,
--   broker_provider text, broker_client_id text,
--   broker_credentials_encrypted text, balance numeric,
--   available_margin numeric, used_margin numeric, status text,
--   locked_reason text, locked_at timestamptz, unlocked_at timestamptz,
--   created_at timestamptz, updated_at timestamptz,
--   daily_profit_cap_until timestamptz, first_payout_approved_at timestamptz
--
-- trading_orders:
--   id uuid, trading_account_id uuid, broker_order_id text,
--   parent_order_id uuid, order_group_id uuid, order_group_type text,
--   symbol text, token text, segment text, instrument_type text,
--   side text, order_type text, product_type text, validity text,
--   qty integer, price numeric, trigger_price numeric, target_price numeric,
--   stoploss_price numeric, trailing_sl numeric, filled_qty integer,
--   pending_qty integer, avg_fill_price numeric, status text,
--   reject_reason text, is_amo boolean, placed_at timestamptz,
--   filled_at timestamptz, cancelled_at timestamptz, updated_at timestamptz,
--   idempotency_key text, correlation_id text
--
-- executions:
--   id uuid, trading_account_id uuid, order_id uuid, position_id uuid,
--   broker_trade_id text, symbol text, token text, segment text,
--   side text, qty integer, price numeric,
--   exchange_timestamp timestamptz, executed_at timestamptz
--
-- positions:
--   id uuid, trading_account_id uuid, symbol text, token text,
--   segment text, instrument_type text, product_type text, side text,
--   qty integer, avg_price numeric, current_price numeric,
--   realized_pnl numeric, unrealized_pnl numeric, buy_qty integer,
--   sell_qty integer, buy_avg numeric, sell_avg numeric,
--   margin_used numeric, is_open boolean, opened_at timestamptz,
--   closed_at timestamptz, updated_at timestamptz
--
-- account_metrics:
--   id uuid, trading_account_id uuid, challenge_id uuid, date date,
--   starting_balance numeric, ending_balance numeric, realized_pnl numeric,
--   unrealized_pnl numeric, total_trades integer, winning_trades integer,
--   losing_trades integer, gross_profit numeric, gross_loss numeric,
--   max_drawdown numeric, daily_loss numeric, peak_balance numeric,
--   avg_win numeric, avg_loss numeric, largest_win numeric,
--   largest_loss numeric, profit_factor numeric
--
-- risk_events:
--   id uuid, trading_account_id uuid, challenge_id uuid, event_type text,
--   severity text, rule_type text, threshold_value numeric,
--   actual_value numeric, metadata jsonb, acknowledged boolean,
--   created_at timestamptz
--
-- watchlists:
--   id uuid, trader_id uuid, name text, color text, icon text,
--   items jsonb, sort_order integer, is_default boolean,
--   created_at timestamptz, updated_at timestamptz
--
-- orders (PAYMENT / CHECKOUT ONLY):
--   id text, user_id text, amount real, account_size integer,
--   plan_type text, status text, payment_method text, utr_reference text,
--   created_at timestamptz, updated_at timestamptz, payment_type text,
--   metadata text
--
-- staff_members:
--   id uuid, email varchar, name varchar, password_hash text,
--   totp_secret text, totp_enabled boolean, status varchar,
--   failed_login_attempts integer, locked_until timestamptz,
--   force_password_change boolean, temp_password_expires_at timestamptz,
--   created_at timestamptz, updated_at timestamptz
--
-- VERIFIED ABSENT FROM THE LIVE DATABASE
--   daily_performance
--   account_metric_snapshots
--   watchlist_items
--   broker_credentials
--   provider_config
--   provider_health
--   terminal_activity
--   terminal_settings
--   employees
--
-- Broker credentials are account-level on trading_accounts. Raw values must
-- remain server-side and broker_credentials_encrypted must never be selected
-- for browser responses.
--
-- Staff authentication mapping is unresolved: staff_members exists, but the
-- live contract does not expose a verified staff_members -> auth.users key.
